//
// This file was generated by MIBGEN. DO NOT EDIT!!!
//

#ifndef ___OBJ_I386_CACHCTRS_H
#define ___OBJ_I386_CACHCTRS_H

//
// Counter definitions:
//

#define CACHE_COUNTER_OBJECT 0
#define CACHE_UrlsInCache 2
#define CACHE_TotalMemoryBytesRetrieved 4
#define CACHE_TotalDiskBytesRetrieved 6
#define CACHE_TotalUrlsCached 8
#define CACHE_TotalMemoryUrlsRetrieved 10
#define CACHE_TotalDiskUrlsRetrieved 12
#define CACHE_MaxUrlsCached 14
#define CACHE_TotalDiskFailures 16
#define CACHE_DiskFailuresRate 18
#define CACHE_MemoryCacheAllocatedSpace 20
#define CACHE_DiskCacheAllocatedSpaceSum 22
#define CACHE_MemoryUsageRatioPercent 24
#define CACHE_ContentDiskWritesRate 26
#define CACHE_MemoryRetrieves 28
#define CACHE_DiskRetrieves 30
#define CACHE_MemoryRetrieveBytes 32
#define CACHE_DiskRetrieveBytes 34
#define CACHE_Commits 36
#endif
