//
// This file was generated by MIBGEN. DO NOT EDIT!!!
//

#ifndef ___OBJ_I386_FWENGPRF_H
#define ___OBJ_I386_FWENGPRF_H

//
// Counter definitions:
//

#define FWENG_COUNTER_OBJ 0
#define COUNTER_ActiveConnections 2
#define COUNTER_NewConnections 4
#define COUNTER_TcpEstablishedConnections 6
#define COUNTER_Bytes 8
#define COUNTER_BytesSecond 10
#define COUNTER_Packets 12
#define COUNTER_PacketsSecond 14
#define COUNTER_AllowedPackets 16
#define COUNTER_AllowedPacketsSecond 18
#define COUNTER_DroppedPackets 20
#define COUNTER_DroppedPacketsSecond 22
#define COUNTER_BackloggedPackets 24
#define COUNTER_RegularConnections 26
#define COUNTER_RegularConnectionsSecond 28
#define COUNTER_TcpNonEstablishedConnections 30
#define COUNTER_TcpNonEstablishedConnectionsSecond 32
#define COUNTER_TcpEstablishedConnectionsSecond 34
#define COUNTER_TcpFinWait1Connections 36
#define COUNTER_TcpFinWait1ConnectionsSecond 38
#define COUNTER_NoTimeoutConnections 40
#define COUNTER_NoTimeoutConnectionsSecond 42
#define COUNTER_ShutdownConnections 44
#define COUNTER_ShutdownConnectionsSecond 46
#define COUNTER_ClosedConnections 48
#define COUNTER_ClosedConnectionsSecond 50
#define COUNTER_NotifyPendingConnections 52
#define COUNTER_NotifyPendingConnectionsSecond 54
#define COUNTER_CreationPendingConnections 56
#define COUNTER_CreationPendingConnectionsSecond 58
#define COUNTER_RawConnection 60
#define COUNTER_RawConnectionSecond 62
#define COUNTER_SpoofedPackets 64
#define COUNTER_SpoofedPacketsSecond 66
#define COUNTER_SynProtections 68
#define COUNTER_SynProtectionsSecond 70
#define COUNTER_FundstoneClosedConnections 72
#define COUNTER_FundstoneClosedConnectionsSecond 74
#define COUNTER_TimeoutTcpEstablishedConnections 76
#define COUNTER_TimeoutTcpEstablishedConnectionsSecond 78
#define COUNTER_TimeoutTcpHalfOpenedConnections 80
#define COUNTER_TimeoutTcpHalfOpenedConnectionsSecond 82
#define COUNTER_TimeoutTcpHalfClosedConnections 84
#define COUNTER_TimeoutTcpHalfClosedConnectionsSecond 86
#define COUNTER_TcpReservePortList 88
#define COUNTER_TcpReservePortListSecond 90
#define COUNTER_UdpReservePortList 92
#define COUNTER_UdpReservePortListSecond 94
#define COUNTER_Creations 96
#define COUNTER_CreationsSecond 98
#define COUNTER_KernelEstablishFailAndDrop 100
#define COUNTER_LogBufferAvailableIRPs 102
#define COUNTER_LogBufferFreeQueueLength 104
#define COUNTER_LogBufferPendingQueueLength 106
#define COUNTER_LogEntriesInCurrentFilledLogEntry 108
#define COUNTER_LogBufferFailedDueToFullQueue 110
#define COUNTER_LogBufferNewPumpFailedDueToFullQueue 112
#define COUNTER_ReInjectAvailableIRPs 114
#define COUNTER_ReInjectFreeQueueLength 116
#define COUNTER_ReInjectPendingHoldPacketsRequests 118
#define COUNTER_ReInjectFailedDueToFullQueue 120
#define COUNTER_NotifyBufferAvailableIRPs 122
#define COUNTER_NotifyBufferFreeQueueLength 124
#define COUNTER_NotifyBufferPendingQueueLength 126
#define COUNTER_NotifyBufferFailedDueToFullQueue 128
#define COUNTER_DroppedBadChecksumPackets 130
#define COUNTER_DroppedSeqAckMismatchPackets 132
#endif
