//
// This file was generated by MIBGEN. DO NOT EDIT!!!
//

#ifndef ___OBJ_I386_HFPERF_H
#define ___OBJ_I386_HFPERF_H

//
// Counter definitions:
//

#define H323FLTR_COUNTER_OBJ 0
#define COUNTER_NumTotalCalls 2
#define COUNTER_NumActiveCalls 4
#endif
