//
// This file was generated by MIBGEN. DO NOT EDIT!!!
//

#ifndef ___OBJ_I386_WSPPERF_H
#define ___OBJ_I386_WSPPERF_H

//
// Counter definitions:
//

#define WSPSRV_COUNTER_OBJ 0
#define COUNTER_ActiveSessions 2
#define COUNTER_ActiveTCPConnections 4
#define COUNTER_ActiveUDPConnections 6
#define COUNTER_ConnectingTCPConnections 8
#define COUNTER_BackConnectingTCPConnections 10
#define COUNTER_AcceptingTCPConnections 12
#define COUNTER_ListeningTCPConnections 14
#define COUNTER_AllocFailureLogs 16
#define COUNTER_PumpTotalRead 18
#define COUNTER_PumpTotalWrite 20
#define COUNTER_PendingGetXByY 22
#define COUNTER_SuccessGetXByY 24
#define COUNTER_FailedGetXByY 26
#define COUNTER_CtrlWorkerThreads 28
#define COUNTER_CtrlAvailableWorkerThreads 30
#define COUNTER_Mappings 32
#define COUNTER_PNATMappings 34
#define COUNTER_KernelDataPumps 36
#define COUNTER_KernelTotalTCPBytes 38
#define COUNTER_KernelTotalUDPBytes 40
#define COUNTER_DnsCacheEntries 42
#define COUNTER_DnsCacheHits 44
#define COUNTER_DnsCacheFlushes 46
#define COUNTER_DnsCacheRetrievals 48
#define COUNTER_DnsCacheRatio 50
#define COUNTER_VpnClientSessions 52
#define COUNTER_VpnClientSessionsSecond 54
#define COUNTER_FwLogFlushRetries 56
#define COUNTER_WebLogFlushRetries 58
#define COUNTER_FwLogEntriesSecond 60
#define COUNTER_WebLogEntriesSecond 62
#define COUNTER_FwRowsFlashedInCurrentBatch 64
#define COUNTER_WebRowsFlashedInCurrentBatch 66
#define COUNTER_KernelConnections 68
#define COUNTER_KernelConnectionsSecond 70
#define COUNTER_RawConnections 72
#define COUNTER_RawConnectionsSecond 74
#define COUNTER_FailedFWCConnect 76
#define COUNTER_FailedFWCConnectSecond 78
#define COUNTER_FailedReinjectConnect 80
#define COUNTER_FailedReinjectConnectSecond 82
#define COUNTER_TimedoutConnections 84
#define COUNTER_TimedoutConnectionsSecond 86
#define COUNTER_EventActions 88
#define COUNTER_EventActionsSecond 90
#define COUNTER_ClosedQuotaConnections 92
#define COUNTER_ClosedQuotaConnectionsSecond 94
#define COUNTER_OutstandingGetHostByNameCalls 96
#define COUNTER_OutstandingGetHostByNameCallsSecond 98
#define COUNTER_OutstandingForwardDnsQueryCalls 100
#define COUNTER_OutstandingForwardDnsQueryCallsSecond 102
#define COUNTER_OutstandingReverseDnsQueryCalls 104
#define COUNTER_OutstandingReverseDnsQueryCallsSecond 106
#define COUNTER_DnsCacheLockFails 108
#define COUNTER_FWLogSizeFirstBuffer 110
#define COUNTER_FWLogSizeSecondBuffer 112
#define COUNTER_ProxyLogSizeFirstBuffer 114
#define COUNTER_ProxyLogSizeSecondBuffer 116
#endif
